name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "BACKEND_URL=${{secrets.BACKEND_URL}}" >> .env
      - name: build docker image
        run: docker build -t sundoladocker/job-resume-frontend .
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: push docker image
        run: docker push sundoladocker/job-resume-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull sundoladocker/job-resume-frontend:latest
      - name: delete old container
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name -e BACKEND_URL=${{ secrets.BACKEND_URL }}  nextjs-app-container sundoladocker/job-resume-frontend